### ISSUE TITLE
Error: can not copy mermaid.js to /usr/lib/draw-graph/mermaid.js

### ISSUE THREAD

**Issue by zcattacz** [LinWanCen/draw-graph#7]
Please consider using user profile base location that don't require superuser write privilege.
Linux desktop environments follow [freedesktop.org defined specs](https://specifications.freedesktop.org/basedir-spec/latest/). e.g. InteliJ places:
generated cache files in `$XDG_CACHE_HOME/JetBrains/IdeaIC***/*`
shared libs in `$XDG_DATA_HOME/JetBrains/IdeaIC***/*`
user configs in `$XDG_CONFIG_HOME/JetBrains/IdeaIC***/*`

```
can not copy mermaid.js to Linux 6.1.0-26-amd64 /usr/lib/draw-graph/mermaid.js

java.nio.file.NoSuchFileException: /usr/lib/draw-graph/mermaid.js
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:482)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:227)
	at java.base/java.nio.file.Files.copy(Files.java:3140)
...
```

**Comment by zcattacz** [comment]
Thank you. Could you also replace GNOME's `nautilus` for `Dir Open` with `xdg-open`, the latter is also part of `free.desktop.org` provided standard tool. https://www.freedesktop.org/wiki/Software/xdg-utils/ .

The `xdg-utils` package is directly required by system `desktop-task` package and many GUI packages e.g. Chromium browser on Debian-based system. It works regardless of user's DE preference.

**Comment by LinWanCen** [comment]
I change it to ScratchPath/extensions/com.github.linwancen.drawgraph
<img width="333" height="536" alt="Image" src="https://github.com/user-attachments/assets/ace4165b-abfb-42b4-a6d6-93801f467231" />
